### PR TITLE
Added a shell script to install external dependencies used by Hasgeek

### PR DESCRIPTION
**Pull request by rudimk**
A basic shell script that install relevant external packages used by Hasgeek apps. Currently supports components used by Lastuser; shall soon also install other packages consumed by the Funnel, HasJob and so on.

### CODE REVIEW

**Comment by jace** [comment]
Just to make this clear, the script should be named `install-ubuntu.sh`. We'll need separate scripts for RPM-based distributions like Fedora and Homebrew-based Macs.

**Comment by rudimk** [comment]
Agreed. Pushing changes, updating PR. Will push a script for RPM-based distros in a bit. Might need a bit of help with the script for Homebrew.

**Comment by caulagi** [comment]
A better approach would be to use something like Ansible (http://www.ansible.com/home) to install dependencies.  For example - https://github.com/caulagi/todo-setup

**Comment by rudimk** [comment]
That's a great idea. However, that does mean you have to be using Ansible,
and that's not always the case - some use Chef, some use Puppet, and so on.
But I reckon we could put that on the table and invite PRs for scripts
catering to different orchestration providers.

**Comment by rudimk** [comment]
Or, we could also just decide on going with Ansible. Installing it isn't a hassle at all, so that can work too.

**Comment by jace** [comment]
Let's try Ansible. It's a good time to reconsider how the production server is setup too.

**Comment by rudimk** [comment]
Sounds like a plan.

**Pull request merged**
